version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./.docker/entrypoint.sh
    container_name: test-nodejs-api-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
